### ISSUE TITLE
关于论文“HiSMatch: Historical Structure Matching based Temporal Knowledge Graph Reasoning”的真诚地询问

### ISSUE THREAD

**Issue by hecccccc** [Lee-zix/HiSMatch#1]
李博士您好！我在阅读您发表在2022 EMNLP上的论文"HiSMatch: Historical Structure Matching based Temporal Knowledge
Graph Reasoning"时遇到了一些问题没有想透彻，比如ConvTransE(hq+heq,r)里向量hq+heq与向量r的维度是否相同，最后的损失函数前是否应该添加一个负号等等，如果您方便的话请问您能发我一份我仅用于个人学习的代码及数据吗(hech18@lzu.edu.cn)？万分感谢！！！

**Comment by Lee-zix** [comment]
The code and datasets have been released. Thanks for your interest.
